/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.*;
import java.io.FileInputStream;
import java.sql.*;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruchi Patel
 */
public class Add_Cylinder_Image extends javax.swing.JFrame {

    /**
     * Creates new form Add_Cylinder_Image
     */
    public Add_Cylinder_Image(String E,int Q) {
        initComponents();
        Email = E;
        Quantity = Q;
        q = Integer.toString(Q);
        LEmail.setText(Email);
        Lquantity.setText(q);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lquantity = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        Select_Image_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Chooser");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose Your Image");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Supplier Email_id:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Quantity of Cylinder:");

        Lquantity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        LEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Select_Image_Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Select_Image_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/select image.png"))); // NOI18N
        Select_Image_Button.setText("Select Image");
        Select_Image_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select_Image_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LEmail)
                                    .addComponent(Lquantity)
                                    .addComponent(Select_Image_Button)))
                            .addComponent(jLabel2))
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Lquantity))
                .addGap(18, 18, 18)
                .addComponent(Select_Image_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Select_Image_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select_Image_ButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser FC = new JFileChooser();
        int i = FC.showOpenDialog(this);
        
        if(i == JFileChooser.APPROVE_OPTION)
        {
            File F = FC.getSelectedFile();
            String Path = F.getPath();
            
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
                Statement st = cn.createStatement();
                String Query = "insert into image(Email,Quantity,Image) values(?,?,?)";
                PreparedStatement ps = cn.prepareStatement(Query);
                ps.setString(1, Email);
                ps.setInt(2, Quantity);
                
                FileInputStream fin = new FileInputStream(Path);
                ps.setBinaryStream(3, fin);
                ps.execute();
                
                JOptionPane.showMessageDialog(rootPane," Successfully Uploaded.");
                
            }
            catch(Exception e)
            {
                System.out.println("Error "+e);
            }
            
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane," Error in Loading Image ");
        }
    }//GEN-LAST:event_Select_Image_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Cylinder_Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Cylinder_Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Cylinder_Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Cylinder_Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Add_Cylinder_Image().setVisible(true);
            }
        });
    }
    
    
    private String Email;
    private String Name;
    private int Quantity;
    private String q;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel Lquantity;
    private javax.swing.JButton Select_Image_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

   
}
