/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruchi Patel
 */
public class Customer_Information extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Information
     */
    public Customer_Information(String CE,String SE,int Q,String Oid) {
        initComponents();
        setDefaultCloseOperation(Customer_Information.DISPOSE_ON_CLOSE);
        dispose();
        
        Customer_Email = CE;
        Supplier_Email = SE;
        Quantity = Q;
        Order_id = Oid;
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("select * from order_cylinder where Customer_Email = '"+Customer_Email+"' and Order_id = '"+Order_id+"' ");
            
            while(rs.next())
            {
                Customer_Email = rs.getString(2);
                Quantity = rs.getInt(4);
                Cost = rs.getInt(5);
                Customer_Address = rs.getString(6);
                Customer_City = rs.getString(7);
                Customer_State = rs.getString(8);
                Ordered_No_of_Cylinder = rs.getInt(9);
                Amount  =rs.getInt(10);
            }
            
            cn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, " Something Went Wrong1 ...");
        }
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("select * from customer_details where Email = '"+Customer_Email+"' ");
            
            while(rs.next())
            {
                Customer_Name = rs.getString(1);
                pincode = rs.getString(5);
                Customer_Contact_No = rs.getString(6);
            }
            
            cn.close();
            
            jLabel1.setText(Customer_Name);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, " Something Went Wrong2 ...");
        }
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("select * from cylinder_information where Email = '"+Supplier_Email+"' and Quantity="+Quantity+" ");
            
            while(rs.next())
            {
                No_of_Cylinder = rs.getString(3);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, " Something Went Wrong3 ...");
        }
        
        Lcustomer_email.setText(Customer_Email);
        LQuantity.setText(Integer.toString(Quantity));
        Lnoofcylinder.setText(No_of_Cylinder);
        Lcost.setText(Integer.toString(Cost));
        Lcustomer_address.setText(Customer_Address);
        Lcustomer_city.setText(Customer_City);
        Lcustomer_name.setText(Customer_Name);
        Lpincode.setText(pincode);
        Lcustomer_contact_no.setText(Customer_Contact_No);
        Lcustomer_state.setText(Customer_State);
        Lrequired_cylinder.setText(Integer.toString(Ordered_No_of_Cylinder));
        Lamount.setText(Integer.toString(Amount));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Lcustomer_contact_no = new javax.swing.JLabel();
        Lpincode = new javax.swing.JLabel();
        Lcustomer_name = new javax.swing.JLabel();
        Lcustomer_city = new javax.swing.JLabel();
        Lcustomer_address = new javax.swing.JLabel();
        Lcost = new javax.swing.JLabel();
        Lnoofcylinder = new javax.swing.JLabel();
        LQuantity = new javax.swing.JLabel();
        Lcustomer_email = new javax.swing.JLabel();
        Lcustomer_state = new javax.swing.JLabel();
        Lrequired_cylinder = new javax.swing.JLabel();
        Lamount = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Information");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Customer Email:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Quantity(in liters):");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Customer's Address:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Customer's City:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Available Cylinders:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Cost Per Cylinder:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Customer Name:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Pincode:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Customer Conatct_No.:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Customer's State:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Required Cylinders:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Amount:");

        Lcustomer_contact_no.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcustomer_contact_no.setText("jLabel7");

        Lpincode.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lpincode.setText("jLabel8");

        Lcustomer_name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcustomer_name.setText("jLabel9");

        Lcustomer_city.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcustomer_city.setText("jLabel17");

        Lcustomer_address.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcustomer_address.setText("jLabel18");

        Lcost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcost.setText("jLabel19");

        Lnoofcylinder.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lnoofcylinder.setText("jLabel20");

        LQuantity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LQuantity.setText("jLabel21");

        Lcustomer_email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcustomer_email.setText("jLabel22");

        Lcustomer_state.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcustomer_state.setText("jLabel23");

        Lrequired_cylinder.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lrequired_cylinder.setText("jLabel24");

        Lamount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lamount.setText("jLabel25");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        jButton1.setText("Order Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close-2-icon.png"))); // NOI18N
        jButton2.setText("Order Cancle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lcustomer_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lcustomer_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lnoofcylinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lcost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lcustomer_city, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lcustomer_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lpincode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lcustomer_contact_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lcustomer_state, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                                    .addComponent(Lrequired_cylinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Lcustomer_email))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LQuantity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Lnoofcylinder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Lcost))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Lcustomer_address, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lcustomer_city)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lcustomer_name)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lpincode)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lcustomer_contact_no)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lcustomer_state)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lrequired_cylinder)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lamount)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            String message = "Hello, "+Customer_Name+" Your Order is Accepted";
            String subject = "Confirmation Regarding Order";
            String to = Customer_Email;
            String from = "oxygencylinderavailability@gmail.com";
            int No_of_Cylinder1 = Integer.parseInt(No_of_Cylinder);
            
            int Updated_No_of_Cylinder = (No_of_Cylinder1) - (Ordered_No_of_Cylinder);
            
            No_of_Cylinder = Integer.toString( Updated_No_of_Cylinder);
            
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
                Statement st = cn.createStatement();

                int i = st.executeUpdate("update Cylinder_information set No_of_Cylinder = '"+No_of_Cylinder+"' where Email = '"+Supplier_Email+"' ");

                if(i == 1)
                {
                    JOptionPane.showMessageDialog(rootPane," Updated Successfully ");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane," Error in Updating .... ");
                }
                cn.close();
            }
            catch(Exception s)
            {
                JOptionPane.showMessageDialog(rootPane," Exception "+s);
            }
            
            
            sendemail(message , subject , to , from);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            String message = "Hello, "+Customer_Name+" Your Order is Cancled";
            String subject = "Confirmation Regarding Order";
            String to = Customer_Email;
            String from = Supplier_Email;
            
            sendemail(message , subject , to , from);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private static void sendemail(String message , String subject , String to , String from)
    {
        //variable for Host
        String host = "smtp.gmail.com";
        
        //Get the System Properties
        Properties properties = System.getProperties();
        System.out.println("PROPERTIES = "+properties);
        
        //Setting import information to properties object
        
        //host set
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "465");
        properties.put("mail.smtp.ssl.enable", "true");
        properties.put("mail.smtp.auth", "true");
        
        //Step 1 : get the session object
        Session session = Session.getInstance(properties , new javax.mail.Authenticator(){
            
             protected PasswordAuthentication getPasswordAuthentication() {
               return new PasswordAuthentication("oxygencylinderavailability@gmail.com","Oxygen1234@"); 
            }
        
        });
        
        session.setDebug(true);

        //Step 2 : Compose the mail
        MimeMessage M = new MimeMessage(session);
        
        
        try
        {
            //From email
            M.setFrom(from);
            
            //adding recipient
            M.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            
            //adding subject to message
            M.setSubject(subject);
            
            //adding text to message
            M.setText(message);
            
            //Step 3 : send the message using Transport Class
            Transport.send(M);
            
            System.out.println("Message is successfully send");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Customer_Information().setVisible(true);
            }
        });
    }
    
    private String Customer_Email;
    private String Supplier_Email;
    private String Customer_Name;
    private String pincode;
    private int Quantity;
    private String Customer_Contact_No;
    private String No_of_Cylinder;
    private int Ordered_No_of_Cylinder;
    private String Customer_Address;
    private String Customer_City;
    private String Customer_State;
    private int Amount;
    private int Cost;
    private String Order_id;
    private String Supplier_Name;
    private String Password;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LQuantity;
    private javax.swing.JLabel Lamount;
    private javax.swing.JLabel Lcost;
    private javax.swing.JLabel Lcustomer_address;
    private javax.swing.JLabel Lcustomer_city;
    private javax.swing.JLabel Lcustomer_contact_no;
    private javax.swing.JLabel Lcustomer_email;
    private javax.swing.JLabel Lcustomer_name;
    private javax.swing.JLabel Lcustomer_state;
    private javax.swing.JLabel Lnoofcylinder;
    private javax.swing.JLabel Lpincode;
    private javax.swing.JLabel Lrequired_cylinder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
